import type { TemplateSeoHub } from '@/lib/template-seo-hubs'

export const AUGUST_2026_TEMPLATE_SEO_HUBS: TemplateSeoHub[] = [
  {
    slug: 'people-operations-dashboard-templates',
    title: 'People Operations Dashboard Templates',
    h1: 'People Operations dashboard templates for HR, recruiting, and workforce analytics',
    eyebrow: 'HR and PeopleOps UI',
    description: 'Explore Next.js people operations dashboard source for organization charts, hiring pipelines, employee directories, attrition analytics, performance reviews, profiles, and HR administration.',
    metaDescription: 'People Operations dashboard templates with org charts, recruiting, employee directories, attrition analytics, reviews, profiles, and Next.js HR source code.',
    keywords: ['people operations dashboard template', 'HR dashboard template', 'Next.js HR admin template', 'employee management dashboard', 'organization chart UI', 'recruiting dashboard template', 'attrition analytics dashboard', 'HRIS interface template'],
    intentTags: ['people operations', 'hr dashboard', 'employee directory', 'organization chart', 'recruiting', 'attrition', 'performance review', 'hris'],
    categoryIds: ['dashboards'],
    priceMode: 'paid',
    introTitle: 'Build around the full employee lifecycle',
    intro: ['A useful HR product connects organizational context, open roles, candidates, employee records, retention signals, review cycles, and administration instead of treating them as unrelated demo screens.', 'Inspect the navigation, detail panels, data tables, bulk actions, permissions boundary, responsive behavior, and empty states before adapting a PeopleOps template to production services.'],
    useCases: ['HRIS products', 'Recruiting platforms', 'People analytics', 'Talent management', 'Workforce operations', 'Internal employee tools'],
    checklist: ['Interactive organization structure', 'Hiring and candidate workflow', 'Searchable employee directory', 'Retention and attrition analytics', 'Performance review lifecycle', 'Profile and settings architecture'],
    faqs: [
      { question: 'Does an HR dashboard template include production employee data security?', answer: 'No. The source provides interface patterns and demonstration data. Production teams must implement server-enforced roles, encryption, audit logs, retention policies, privacy controls, and approved HR system integrations.' },
      { question: 'Can Bloom be connected to an HRIS or recruiting system?', answer: 'Yes. Its typed demo data and separated UI provide a clear replacement boundary for HRIS, ATS, identity, payroll, or analytics APIs.' },
    ],
    related: ['enterprise-dashboard-templates', 'nextjs-dashboard-templates', 'saas-templates'],
  },
  {
    slug: 'retail-operations-dashboard-templates',
    title: 'Retail Operations Dashboard Templates',
    h1: 'Retail operations dashboard templates for products, orders, inventory, and fulfillment',
    eyebrow: 'Retail and DTC admin UI',
    description: 'Find Next.js retail dashboard source for merchandising, product catalogs, order management, fulfillment, inventory health, replenishment, sales analytics, and ecommerce operations.',
    metaDescription: 'Retail operations dashboard templates with products, orders, inventory, fulfillment, replenishment, analytics, and Next.js ecommerce admin source.',
    keywords: ['retail operations dashboard template', 'ecommerce admin dashboard', 'DTC dashboard template', 'inventory management UI', 'order fulfillment dashboard', 'product catalog admin template', 'restock dashboard', 'Next.js retail dashboard'],
    intentTags: ['retail operations', 'dtc', 'merchandising', 'inventory management', 'order fulfillment', 'product catalog', 'restock', 'retail analytics'],
    categoryIds: ['dashboards'],
    priceMode: 'paid',
    introTitle: 'Connect merchandising decisions to fulfillment reality',
    intro: ['Retail operators move between product performance, order exceptions, stock health, replenishment, customers, and channel context throughout the day. A template should preserve these relationships across its overview and working screens.', 'Review data density with realistic product names and images, confirm order actions communicate state safely, and test low-stock workflows at both desktop and mobile widths.'],
    useCases: ['DTC brand operations', 'Ecommerce administration', 'Order management systems', 'Inventory SaaS', 'Retail analytics', 'Fulfillment platforms'],
    checklist: ['Product discovery and quick view', 'Sortable order operations table', 'Order detail and status workflow', 'Inventory health and low-stock signals', 'Validated replenishment actions', 'Responsive search and navigation'],
    faqs: [
      { question: 'Does Aisle connect to Shopify or another commerce backend?', answer: 'The package ships with realistic deterministic demo data. Connect your chosen commerce, warehouse, payment, and shipping services through a server-side integration layer.' },
      { question: 'Are the product images included?', answer: 'Aisle includes 99 product photographs across 33 product families plus customer portraits for its demonstration catalog and order workflows.' },
    ],
    related: ['enterprise-dashboard-templates', 'nextjs-dashboard-templates', 'ecommerce-website-templates'],
  },
  {
    slug: 'inventory-forecasting-saas-templates',
    title: 'Inventory Forecasting SaaS Templates',
    h1: 'Inventory forecasting SaaS templates for demand planning and replenishment products',
    eyebrow: 'Inventory intelligence websites',
    description: 'Browse landing page source for demand forecasting, SKU velocity, replenishment, purchase orders, multichannel inventory, retail analytics, pricing, integrations, and lead generation.',
    metaDescription: 'Inventory forecasting SaaS templates for demand planning, replenishment, purchase orders, retail analytics, pricing, integrations, and Next.js landing pages.',
    keywords: ['inventory forecasting SaaS template', 'demand planning landing page', 'replenishment software website', 'inventory intelligence template', 'supply chain SaaS landing page', 'retail analytics website template', 'Next.js B2B SaaS landing page'],
    intentTags: ['inventory forecasting', 'demand forecasting', 'demand planning', 'replenishment', 'purchase order', 'inventory intelligence', 'supply-chain'],
    categoryIds: ['landing'],
    priceMode: 'paid',
    introTitle: 'Explain predictive value with operational evidence',
    intro: ['Inventory software must connect a forecast to the daily decisions it improves: what to order, when to order, how much to hold, and where risk is building across SKUs and channels.', 'A strong landing template supports that explanation with believable product visuals, quantified customer outcomes, implementation detail, pricing context, integrations, operational FAQs, and a low-friction sales path.'],
    useCases: ['Demand forecasting SaaS', 'Inventory intelligence', 'Replenishment automation', 'Retail planning software', 'Supply-chain startups', 'Multichannel commerce tools'],
    checklist: ['Forecast-led product hero', 'Operational product visualizations', 'Quantified outcomes and proof', 'Implementation and integration story', 'Pricing and FAQ sections', 'Validated contact or demo flow'],
    faqs: [
      { question: 'Is Cadence only for inventory forecasting products?', answer: 'Its content and visual system are purpose-built for inventory, demand planning, replenishment, and retail operations, but the typed content structure can be adapted to adjacent operational SaaS products.' },
      { question: 'Do the contact forms send production email?', answer: 'The included handlers validate submissions and document the integration point. Connect an approved email or CRM provider and add spam, rate-limit, consent, and monitoring controls before launch.' },
    ],
    related: ['saas-templates', 'landing-page-templates', 'ecommerce-website-templates'],
  },
  {
    slug: 'ai-saas-website-templates',
    title: 'AI SaaS Website Templates',
    h1: 'AI SaaS website templates with marketing, documentation, auth, and dashboard UI',
    eyebrow: 'AI product launch systems',
    description: 'Explore enterprise Next.js AI SaaS templates with conversion pages, pricing, blog, documentation, authentication, customer dashboards, billing, teams, integrations, legal pages, and SEO infrastructure.',
    metaDescription: 'AI SaaS website templates with landing pages, pricing, blog, docs, auth, dashboard, billing, teams, integrations, legal pages, and Next.js source.',
    keywords: ['AI SaaS website template', 'Next.js AI landing page', 'enterprise SaaS template', 'AI dashboard template', 'SaaS documentation template', 'AI startup website source code', 'developer platform template', 'B2B SaaS application UI'],
    intentTags: ['ai workspace', 'ai saas', 'artificial intelligence', 'developer platform', 'automation product'],
    categoryIds: ['landing'],
    priceMode: 'paid',
    introTitle: 'Launch a complete product surface, not only a hero section',
    intro: ['AI SaaS buyers often need product education, security context, pricing clarity, documentation, account creation, billing visibility, integrations, and ongoing product communication before they can adopt a new platform.', 'Evaluate whether the template connects these surfaces through consistent navigation, tokens, content configuration, responsive behavior, metadata, forms, and an application shell that can be integrated with real identity and billing systems.'],
    useCases: ['AI workspaces', 'Automation SaaS', 'Developer platforms', 'Analytics products', 'Enterprise AI tools', 'Subscription software launches'],
    checklist: ['Conversion-focused marketing narrative', 'Dedicated pricing and comparison', 'Documentation and content engine', 'Authentication and account flows', 'Customer dashboard and billing', 'Sitemap, structured data, and social assets'],
    faqs: [
      { question: 'Does Ion include a backend AI model integration?', answer: 'Ion provides the website, interface, forms, API integration points, and demonstration application. Connect your model provider, data services, authentication, metering, billing, and security controls for production.' },
      { question: 'How much of the website is included?', answer: 'Ion includes 47 real routes spanning marketing, pricing, blog, docs, changelog, company, careers, community, auth, dashboard, billing, team, integrations, activity, and legal content.' },
    ],
    related: ['saas-templates', 'nextjs-dashboard-templates', 'landing-page-templates'],
  },
]
