import type { TemplateSeoHub } from '@/lib/template-seo-hubs'

export const ENTERPRISE_DASHBOARD_SEO_HUBS: TemplateSeoHub[] = [
  {
    slug: 'enterprise-dashboard-templates',
    title: 'Enterprise Dashboard Templates',
    h1: 'Enterprise dashboard templates for operational and data-intensive products',
    eyebrow: 'Enterprise application UI',
    description: 'Explore enterprise Next.js dashboard templates for fleet operations, healthcare workflows, trading terminals, SaaS analytics, CRM, finance, logistics, and internal administration.',
    metaDescription: 'Enterprise dashboard templates for fleet, healthcare, trading, SaaS analytics, logistics, finance, and admin products. Next.js source, previews, and secure ZIP delivery.',
    keywords: ['enterprise dashboard templates', 'enterprise admin dashboard', 'Next.js enterprise dashboard', 'React enterprise admin template', 'operational dashboard UI', 'data intensive dashboard', 'enterprise SaaS template', 'internal tools dashboard'],
    intentTags: ['enterprise', 'operations', 'clinical', 'trading', 'analytics', 'logistics', 'admin', 'dashboard'],
    categoryIds: ['dashboards'],
    priceMode: 'paid',
    introTitle: 'Dashboard foundations built around real operating models',
    intro: ['Enterprise dashboards need clear navigation, dense but readable information, advanced tables, actionable queues, reliable detail views, settings, and states that survive real data.', 'This collection keeps every template in the normal dashboard catalog while grouping high-intent enterprise use cases for easier comparison. Inspect the live preview and included workflows before choosing a source package.'],
    useCases: ['Operations control centers', 'Healthcare platforms', 'Trading and investment products', 'SaaS revenue operations', 'Logistics software', 'Internal enterprise tools'],
    checklist: ['Industry-specific workflows', 'Responsive application shell', 'Advanced tables and data visualization', 'Light and dark themes where included', 'Typed source-code package', 'Secure buyer-only ZIP delivery'],
    faqs: [
      { question: 'Are enterprise templates listed separately from other dashboards?', answer: 'No. They remain in the main dashboard catalog. This page is an additional search and comparison hub for enterprise use cases.' },
      { question: 'Does a template provide production authentication and business integrations?', answer: 'Templates provide the interface foundation and documented integration points. Production authentication, authorization, databases, APIs, compliance, monitoring, and organization-specific business rules must be connected by the implementation team.' },
    ],
    related: ['nextjs-dashboard-templates', 'react-admin-dashboard-templates', 'saas-templates'],
  },
  {
    slug: 'fleet-management-dashboard-templates',
    title: 'Fleet Management Dashboard Templates',
    h1: 'Fleet management dashboard templates for dispatch, vehicles, routes, and logistics',
    eyebrow: 'Fleet operations UI',
    description: 'Find dashboard source for live fleet monitoring, dispatch queues, vehicle tables, route timelines, driver performance, warehouses, incidents, alerts, and logistics analytics.',
    metaDescription: 'Fleet management dashboard templates with dispatch, vehicle tracking, route planning, drivers, warehouses, incidents, analytics, maps, and Next.js source.',
    keywords: ['fleet management dashboard template', 'logistics dashboard template', 'dispatch dashboard UI', 'vehicle tracking dashboard', 'route planning dashboard', 'transportation admin template', 'fleet SaaS template'],
    intentTags: ['fleet', 'dispatch', 'vehicle', 'route', 'driver', 'warehouse', 'logistics', 'transportation'],
    categoryIds: ['dashboards'],
    priceMode: 'paid',
    introTitle: 'Operational views for moving fleets',
    intro: ['Fleet products need to connect vehicles, drivers, routes, warehouses, assignments, incidents, and service commitments in one understandable workspace.', 'Use the live preview to inspect map behavior, table density, queue actions, route timing, responsive navigation, and operational states before adapting the source.'],
    useCases: ['Last-mile delivery', 'Field-service dispatch', 'Transportation management', 'Vehicle telematics', 'Warehouse logistics', 'Fleet maintenance operations'],
    checklist: ['Fleet status overview', 'Map and vehicle context', 'Dispatch and escalation queues', 'Route and warehouse workflows', 'Driver performance views', 'Operational analytics and alerts'],
    faqs: [{ question: 'Does the FleetOps template include real GPS tracking?', answer: 'The source includes a working map interface and deterministic demonstration data. Connect your approved telematics, routing, and mapping services for production tracking.' }, { question: 'Can I use it for delivery or field service?', answer: 'Yes. The workflow foundation can be adapted to delivery, transport, field-service, maintenance, and other vehicle-based operations.' }],
    related: ['enterprise-dashboard-templates', 'nextjs-dashboard-templates', 'react-admin-dashboard-templates'],
  },
  {
    slug: 'healthcare-dashboard-templates',
    title: 'Healthcare Dashboard Templates',
    h1: 'Healthcare dashboard templates for patient and clinical operations',
    eyebrow: 'Clinical workflow UI',
    description: 'Explore healthcare dashboard source for patient rosters, vitals, medications, visit timelines, appointments, care teams, tasks, alerts, reports, and administration.',
    metaDescription: 'Healthcare dashboard templates for patient rosters, vitals, medications, appointments, care teams, tasks, alerts, reports, and Next.js clinical UI.',
    keywords: ['healthcare dashboard template', 'medical admin dashboard', 'patient management dashboard', 'clinical dashboard UI', 'hospital dashboard template', 'care coordination dashboard', 'Next.js healthcare template'],
    intentTags: ['healthcare', 'clinical', 'patient', 'medical', 'hospital', 'care', 'vitals', 'medications'],
    categoryIds: ['dashboards'],
    priceMode: 'paid',
    introTitle: 'Patient context and care coordination patterns',
    intro: ['Healthcare interfaces need clear patient identity, current status, clinical context, responsibilities, and time-sensitive work without overwhelming staff.', 'These templates are UI foundations, not medical devices or compliance guarantees. Production teams must connect approved systems and implement privacy, access, validation, audit, and clinical governance controls.'],
    useCases: ['Hospital operations', 'Patient management SaaS', 'Care coordination', 'Outpatient workflows', 'Provider administration', 'Healthcare product prototypes'],
    checklist: ['Patient roster and search', 'Clinical detail tabs', 'Appointments and care teams', 'Tasks, alerts, and reports', 'Accessible responsive layout', 'Clear data integration boundaries'],
    faqs: [{ question: 'Is a healthcare template HIPAA compliant by itself?', answer: 'No. Compliance depends on the full deployed system, vendors, contracts, infrastructure, policies, access controls, audit practices, and organizational procedures.' }, { question: 'Does Meridian Health include live patient data?', answer: 'No. It ships with deterministic demonstration data that must be replaced with approved authenticated services for production use.' }],
    related: ['enterprise-dashboard-templates', 'nextjs-dashboard-templates', 'saas-templates'],
  },
  {
    slug: 'trading-dashboard-templates',
    title: 'Trading Dashboard Templates',
    h1: 'Trading dashboard templates for markets, orders, portfolios, and fintech products',
    eyebrow: 'Trading terminal UI',
    description: 'Browse trading and investment dashboard source with watchlists, market charts, order books, order tickets, positions, orders, portfolio analytics, alerts, and history.',
    metaDescription: 'Trading dashboard templates with watchlists, charts, order books, order entry, positions, portfolio analytics, alerts, history, and responsive Next.js UI.',
    keywords: ['trading dashboard template', 'investment dashboard template', 'fintech dashboard UI', 'stock market dashboard', 'portfolio dashboard template', 'order book UI', 'Next.js finance dashboard'],
    intentTags: ['trading', 'investment', 'market', 'portfolio', 'order', 'fintech', 'finance', 'stock'],
    categoryIds: ['dashboards'],
    priceMode: 'paid',
    introTitle: 'High-density workspaces for market products',
    intro: ['Trading dashboards need synchronized market context, efficient navigation, deliberate order actions, portfolio visibility, and supporting account controls.', 'The source templates use demonstration market data and simulated interactions. Production execution, risk controls, licensed feeds, permissions, reconciliation, and regulatory requirements remain implementation responsibilities.'],
    useCases: ['Brokerage product prototypes', 'Investment analytics', 'Wealth platforms', 'Portfolio monitoring', 'Fintech administration', 'Internal trading tools'],
    checklist: ['Watchlist and chart context', 'Order book and ticket patterns', 'Positions, orders, and history', 'Portfolio analytics and alerts', 'Desktop and mobile workflows', 'Account and security settings'],
    faqs: [{ question: 'Does the template place real trades?', answer: 'No. Order entry and market updates are demonstration UI. A production product must connect licensed data and brokerage infrastructure with server-side validation, security, and risk controls.' }, { question: 'Is there a mobile layout?', answer: 'Meridian Terminal includes a dedicated compact mobile shell in addition to its multi-panel desktop workspace.' }],
    related: ['enterprise-dashboard-templates', 'nextjs-dashboard-templates', 'react-admin-dashboard-templates'],
  },
  {
    slug: 'saas-analytics-dashboard-templates',
    title: 'SaaS Analytics Dashboard Templates',
    h1: 'SaaS analytics dashboard templates for MRR, churn, customers, and billing',
    eyebrow: 'Subscription analytics UI',
    description: 'Find SaaS analytics dashboard source for revenue KPIs, MRR movements, churn, funnels, customers, subscriptions, plans, usage, invoices, teams, API keys, and support.',
    metaDescription: 'SaaS analytics dashboard templates for MRR, churn, revenue, customers, billing, invoices, usage, teams, API keys, and production-ready Next.js UI.',
    keywords: ['SaaS analytics dashboard template', 'MRR dashboard template', 'churn analytics dashboard', 'subscription dashboard UI', 'customer management dashboard', 'billing dashboard template', 'Next.js SaaS admin'],
    intentTags: ['saas', 'mrr', 'churn', 'subscription', 'revenue', 'customer', 'billing', 'analytics'],
    categoryIds: ['dashboards'],
    priceMode: 'paid',
    introTitle: 'Connect subscription metrics to operating workflows',
    intro: ['SaaS teams need more than top-level revenue charts. Customer management, plan usage, invoices, payment methods, team roles, API access, documentation, and support turn analytics into an operational product.', 'Use these templates to accelerate the interface layer, then connect a documented metric model and verified billing events on the server.'],
    useCases: ['Subscription SaaS', 'Revenue operations', 'Customer success platforms', 'B2B analytics', 'Billing administration', 'Startup admin portals'],
    checklist: ['MRR and churn metrics', 'Revenue and funnel charts', 'Customer management table', 'Plans, usage, and invoices', 'Team and API administration', 'Auth, support, and docs'],
    faqs: [{ question: 'Are MRR and churn calculations included as production logic?', answer: 'The template demonstrates metrics with deterministic data. Define and calculate production metrics in a documented server-side data model connected to your billing and product events.' }, { question: 'Can the dashboard work with Stripe or Paddle?', answer: 'Yes, but provider APIs, signed webhooks, reconciliation, permissions, and entitlement logic need to be implemented for the chosen billing platform.' }],
    related: ['saas-templates', 'enterprise-dashboard-templates', 'nextjs-dashboard-templates'],
  },
]
