export type UiComponentExample = {
  name: string
  slug: string
  description: string
}

export type UiComponentSeoHub = {
  slug: string
  title: string
  h1: string
  eyebrow: string
  metaDescription: string
  description: string
  keywords: string[]
  useCases: string[]
  introTitle: string
  intro: string[]
  checklist: string[]
  examples: UiComponentExample[]
  faqs: Array<{ question: string; answer: string }>
  related: string[]
}

const component = (name: string, slug: string, description: string): UiComponentExample => ({
  name,
  slug,
  description,
})

const examples = {
  navbar: component('Responsive Navbar', 'navbar001-card', 'A responsive application navbar with desktop and mobile navigation states.'),
  sidebar: component('Arctic Frost Sidebar', 'arctic-frost-sidebar-card', 'A structured product sidebar for dashboards and admin workspaces.'),
  buttons: component('Premium Animated Buttons', 'premium-animated-buttons-card', 'Polished action buttons with clear hierarchy and interaction feedback.'),
  input: component('Animated Floating Input', 'animated-floating-input-card', 'A form input pattern with labels, focus states, and validation-ready structure.'),
  modal: component('Confirmation Dialog', 'confirmation-dialog-card', 'A focused confirmation flow for destructive or high-impact actions.'),
  table: component('Enterprise Data Table', 'enterprise-table-card', 'A dense data display pattern for operational dashboards and internal tools.'),
  hero: component('Modern Hero Section', 'hero001-card', 'A responsive marketing hero for product, SaaS, and launch pages.'),
  pricing: component('Pricing Comparison', 'pricing001-card', 'A pricing layout that makes plans, features, and calls to action easy to compare.'),
  notification: component('Notification Panel', 'notification-panel-card', 'A compact notification experience for product events and account updates.'),
  command: component('Command Palette', 'command-palette-card', 'A keyboard-friendly command surface for fast product navigation.'),
  dashboard: component('Dashboard Insight Block', 'insight-bento-dashboard-card', 'A dashboard block for metrics, summaries, and decision-ready product data.'),
  auth: component('Authentication Screen', 'auth009-card', 'A responsive sign-in and account access screen for web products.'),
}

export const UI_COMPONENT_SEO_HUBS: UiComponentSeoHub[] = [
  {
    slug: 'modern-ui-components',
    title: 'Modern UI Components for Web Products',
    h1: 'Modern UI components for polished web products',
    eyebrow: 'Modern interface patterns',
    metaDescription: 'Explore modern UI components for dashboards, SaaS products, ecommerce, and landing pages with responsive previews and production-ready React source.',
    description: 'Browse focused interface patterns for navigation, forms, data display, overlays, product workflows, and marketing pages. Every example can be previewed before source access.',
    keywords: ['modern UI components', 'modern web components', 'modern UI design', 'responsive UI components', 'production ready UI components'],
    useCases: ['SaaS products', 'Admin dashboards', 'Ecommerce', 'Internal tools', 'Landing pages', 'AI interfaces'],
    introTitle: 'What makes a UI component useful in production?',
    intro: [
      'A modern component is more than a visual effect. It needs clear hierarchy, responsive behavior, accessible controls, stable layout, and states for loading, empty data, errors, and user actions.',
      'Use this collection to compare real interface patterns before implementation. Start with the workflow, choose the smallest suitable component, and adapt tokens and copy to match your product rather than assembling unrelated visual fragments.',
    ],
    checklist: ['Responsive across phone, tablet, and desktop widths', 'Keyboard and focus behavior for interactive controls', 'Loading, empty, success, and error states where relevant', 'Consistent spacing, type scale, and design tokens', 'Source that can be adapted without hiding core behavior'],
    examples: [examples.navbar, examples.sidebar, examples.dashboard, examples.modal, examples.buttons, examples.hero],
    faqs: [
      { question: 'What are modern UI components?', answer: 'Modern UI components are reusable interface patterns designed for current web products, with responsive layouts, clear states, accessible interactions, and adaptable styling.' },
      { question: 'Can I use these components in a production project?', answer: 'You can inspect every preview publicly. Lifetime source access includes the protected component code, implementation notes, dependencies, and future library updates.' },
      { question: 'Are the components only for dashboards?', answer: 'No. The library covers dashboard, SaaS, ecommerce, marketing, authentication, navigation, forms, data display, and product workflow patterns.' },
    ],
    related: ['react-ui-components', 'nextjs-ui-components', 'dashboard-ui-components', 'landing-page-ui-blocks'],
  },
  {
    slug: 'react-ui-components',
    title: 'React UI Components',
    h1: 'Reusable React UI components with responsive previews',
    eyebrow: 'React component library',
    metaDescription: 'Browse reusable React UI components for navigation, forms, tables, dialogs, dashboards, and SaaS interfaces with live responsive previews.',
    description: 'Find React interface patterns that separate reusable presentation from product-specific data and actions. Preview components first, then review source and implementation guidance with lifetime access.',
    keywords: ['React UI components', 'React component library', 'reusable React components', 'React dashboard components', 'React UI blocks'],
    useCases: ['React applications', 'Design systems', 'SaaS interfaces', 'Admin portals', 'Customer dashboards', 'Product prototypes'],
    introTitle: 'Choosing reusable React components',
    intro: [
      'Good React components expose clear inputs, preserve semantic HTML, and keep business logic outside the visual layer. This makes them easier to test, compose, and update as a product grows.',
      'Start with components that solve a real workflow such as navigation, filtering, confirmation, or data review. Reuse shared primitives and tokens so new screens feel related instead of becoming a collection of one-off styles.',
    ],
    checklist: ['Clear props and predictable composition', 'Semantic markup and accessible labels', 'Controlled state where product logic requires it', 'Reusable styling through shared tokens', 'No hidden dependency on demo-only data'],
    examples: [examples.input, examples.table, examples.modal, examples.notification, examples.command, examples.auth],
    faqs: [
      { question: 'Are these copy-and-use React components?', answer: 'The component previews are public. Source access provides the component files, dependencies, and implementation details so you can integrate and adapt them in your React project.' },
      { question: 'Do the React components include TypeScript?', answer: 'The library is structured for modern React and TypeScript projects, with typed implementation patterns and documented dependencies where they are required.' },
      { question: 'Can I restyle the components?', answer: 'Yes. The source is intended to be adapted to your design tokens, product copy, data, and workflow requirements.' },
    ],
    related: ['modern-ui-components', 'nextjs-ui-components', 'tailwind-css-components', 'form-components'],
  },
  {
    slug: 'nextjs-ui-components',
    title: 'Next.js UI Components',
    h1: 'Next.js UI components for product pages and dashboards',
    eyebrow: 'Next.js interface library',
    metaDescription: 'Explore Next.js UI components and blocks for dashboards, navigation, authentication, pricing, forms, tables, and modern product interfaces.',
    description: 'Use preview-first Next.js component patterns for application routes, marketing pages, authenticated screens, and data-heavy dashboards.',
    keywords: ['Next.js UI components', 'Next.js components', 'Next.js component library', 'Next.js dashboard components', 'Next.js UI blocks'],
    useCases: ['App Router projects', 'Server-rendered products', 'Next.js dashboards', 'Marketing sites', 'Account portals', 'SaaS applications'],
    introTitle: 'Building component-driven Next.js interfaces',
    intro: [
      'In a Next.js project, the best component boundary also respects rendering behavior. Keep interactive client code focused, render stable content on the server where practical, and avoid moving entire pages to the client for a small interaction.',
      'These examples help you compare navigation, forms, dialogs, data views, and marketing blocks while keeping implementation choices visible. Adapt each pattern to your route data, caching strategy, and accessibility requirements.',
    ],
    checklist: ['Small and intentional client component boundaries', 'Stable server and client output to avoid hydration issues', 'Responsive images and predictable dimensions', 'Metadata and semantic page structure for public routes', 'Loading and error UI for asynchronous workflows'],
    examples: [examples.navbar, examples.auth, examples.dashboard, examples.pricing, examples.table, examples.hero],
    faqs: [
      { question: 'Do these components work with the Next.js App Router?', answer: 'The source patterns are built for modern React and Next.js workflows. Each interactive component should be integrated with the correct client boundary for your application.' },
      { question: 'Are Next.js metadata and SEO included in individual components?', answer: 'UI components focus on interface behavior. Public pages still need route-level metadata, useful content, canonical URLs, and structured data where appropriate.' },
      { question: 'Can the same component be used in a React project without Next.js?', answer: 'Many visual components can be reused in React projects, but Next.js-specific imports or routing behavior should be replaced with equivalents from your stack.' },
    ],
    related: ['react-ui-components', 'modern-ui-components', 'dashboard-ui-components', 'landing-page-ui-blocks'],
  },
  {
    slug: 'tailwind-css-components',
    title: 'Tailwind CSS UI Components',
    h1: 'Tailwind CSS components for consistent product interfaces',
    eyebrow: 'Utility-first UI patterns',
    metaDescription: 'Browse Tailwind CSS UI components for buttons, forms, navigation, dashboards, tables, modals, and landing page sections.',
    description: 'Explore utility-first component patterns with consistent spacing, responsive constraints, state styling, and design-token-friendly structure.',
    keywords: ['Tailwind CSS components', 'Tailwind UI components', 'Tailwind React components', 'Tailwind component library', 'Tailwind UI blocks'],
    useCases: ['Tailwind design systems', 'Responsive interfaces', 'Rapid product development', 'React applications', 'Next.js projects', 'UI prototyping'],
    introTitle: 'Using Tailwind without creating inconsistent screens',
    intro: [
      'Utility classes speed up implementation, but consistency still comes from shared decisions. Define tokens for color, spacing, radius, typography, and focus states before repeating long class lists across a product.',
      'Treat these components as structured starting points. Extract recurring variants, keep responsive behavior explicit, and remove decorative styles that do not support the workflow or brand.',
    ],
    checklist: ['Shared color and spacing tokens', 'Responsive classes tied to real layout needs', 'Reusable variants for recurring controls', 'Visible hover, focus, disabled, and error states', 'Readable class composition and minimal duplication'],
    examples: [examples.buttons, examples.input, examples.navbar, examples.sidebar, examples.modal, examples.pricing],
    faqs: [
      { question: 'Are these Tailwind components free to preview?', answer: 'Yes. Component previews are publicly accessible. Protected source and implementation documentation are included with lifetime library access.' },
      { question: 'Can I use a different Tailwind theme?', answer: 'Yes. Replace the example tokens and utility values with your project theme while preserving accessible states and layout behavior.' },
      { question: 'Do I need every dependency used by the full library?', answer: 'No. Install only the dependencies required by the components you integrate. The documentation identifies component-specific requirements.' },
    ],
    related: ['react-ui-components', 'button-components', 'form-components', 'modern-ui-components'],
  },
  {
    slug: 'navbar-components',
    title: 'Navbar Components',
    h1: 'Responsive navbar components for modern websites and apps',
    eyebrow: 'Navigation components',
    metaDescription: 'Preview responsive navbar components for SaaS, ecommerce, dashboards, and landing pages with mobile menus and accessible navigation patterns.',
    description: 'Compare navbar patterns for public websites and authenticated products, including responsive menus, search, account actions, and compact application navigation.',
    keywords: ['navbar components', 'React navbar component', 'Next.js navbar', 'responsive navbar UI', 'modern navigation component'],
    useCases: ['Marketing websites', 'SaaS products', 'Ecommerce stores', 'Dashboards', 'Documentation', 'Mobile navigation'],
    introTitle: 'Designing navigation that stays clear',
    intro: [
      'A navbar should make the current location, primary destinations, and next action easy to understand. On small screens, reduce choices and preserve access to account and critical product actions.',
      'Choose a pattern based on information architecture rather than visual novelty. Keep keyboard navigation, focus order, touch targets, and overflow behavior reliable before adding motion.',
    ],
    checklist: ['Clear primary and secondary destinations', 'Mobile menu with controlled focus and dismissal', 'Current-page indication', 'Predictable search and account actions', 'Stable height that avoids layout shift'],
    examples: [examples.navbar, examples.command, examples.notification, examples.auth],
    faqs: [
      { question: 'What should a responsive navbar include?', answer: 'A responsive navbar should preserve the most important destinations, provide a clear mobile menu, support keyboard navigation, and keep account or checkout actions easy to find.' },
      { question: 'Can I use a navbar component in Next.js?', answer: 'Yes. Replace links and client interactions with the routing and state patterns used by your Next.js project.' },
      { question: 'Should every nav item remain visible on mobile?', answer: 'Usually not. Prioritize the brand, current task, and one or two key actions, then place the remaining destinations in an accessible drawer or menu.' },
    ],
    related: ['sidebar-components', 'nextjs-ui-components', 'modern-ui-components'],
  },
  {
    slug: 'sidebar-components',
    title: 'Sidebar Components',
    h1: 'Modern sidebar components for dashboards and SaaS apps',
    eyebrow: 'Application navigation',
    metaDescription: 'Browse modern sidebar components for admin dashboards, SaaS products, internal tools, and responsive application shells.',
    description: 'Explore compact, collapsible, and full navigation sidebars designed for dense product workflows and responsive application layouts.',
    keywords: ['sidebar components', 'React sidebar component', 'dashboard sidebar', 'modern sidebar UI', 'Next.js sidebar navigation'],
    useCases: ['Admin dashboards', 'Internal tools', 'SaaS workspaces', 'Analytics products', 'CRM interfaces', 'Operations portals'],
    introTitle: 'Choosing the right dashboard sidebar',
    intro: [
      'Sidebars work best when they organize repeat workflows into a stable hierarchy. Labels, groups, active states, and collapse behavior should help users scan quickly without hiding important context.',
      'A responsive application may switch from a persistent desktop sidebar to a mobile drawer. Keep the same information architecture in both modes and avoid changing labels or destination order unnecessarily.',
    ],
    checklist: ['Visible active state and clear section groups', 'Collapsed mode with tooltips or recognizable labels', 'Mobile drawer behavior and reliable dismissal', 'Scroll handling for long navigation lists', 'Account and sign-out actions separated from primary navigation'],
    examples: [examples.sidebar, component('Command Center Sidebar', 'command-center-sidebar-card', 'A work-focused sidebar for dense dashboard navigation.'), component('Compact Pill Sidebar', 'compact-pill-sidebar-card', 'A compact navigation pattern for smaller application shells.'), examples.dashboard],
    faqs: [
      { question: 'When should I use a sidebar instead of a navbar?', answer: 'Use a sidebar when a product has many recurring destinations or grouped workflows. Simpler websites usually work better with a top navigation bar.' },
      { question: 'Should a dashboard sidebar collapse?', answer: 'Collapsing can recover workspace width, but icons need clear meaning and tooltips. Preserve the active location and make expansion easy.' },
      { question: 'How should a sidebar work on mobile?', answer: 'Use an accessible drawer or sheet with clear dismissal, focus management, and the same destination structure as desktop.' },
    ],
    related: ['navbar-components', 'dashboard-ui-components', 'modern-ui-components'],
  },
  {
    slug: 'button-components',
    title: 'Modern Button UI Components',
    h1: 'Modern button components with clear interaction states',
    eyebrow: 'Action components',
    metaDescription: 'Preview modern button UI components for React and Next.js with primary, secondary, loading, disabled, icon, and destructive states.',
    description: 'Find button patterns for primary actions, toolbars, loading flows, destructive commands, and compact icon controls.',
    keywords: ['modern button UI', 'button components', 'React button component', 'Tailwind buttons', 'animated button components'],
    useCases: ['Primary CTAs', 'Form submission', 'Toolbars', 'Checkout actions', 'Loading states', 'Destructive actions'],
    introTitle: 'Buttons should communicate consequence',
    intro: [
      'A button needs a clear label, sufficient contrast, a stable hit area, and visible hover, focus, pressed, loading, and disabled states. Visual priority should match the importance of the action.',
      'Use animation sparingly and never let it change layout or obscure the label. Familiar icons can support compact tools, but unfamiliar actions still need text or a tooltip.',
    ],
    checklist: ['Primary, secondary, and destructive hierarchy', 'Visible keyboard focus', 'Stable loading state that prevents duplicate actions', 'Disabled state with sufficient context', 'Icon buttons with accessible names and tooltips'],
    examples: [examples.buttons, component('Liquid Metal Buttons', 'liquid-metal-buttons-card', 'Expressive button treatments for selected high-emphasis actions.'), component('Loading State Buttons', 'loading-state-buttons-card', 'Stable loading and progress states for asynchronous actions.'), component('Premium CTA Buttons', 'premium-cta-buttons-card', 'Call-to-action buttons for product and pricing surfaces.')],
    faqs: [
      { question: 'What states should a button component support?', answer: 'At minimum, support default, hover, focus, active, disabled, and loading states. Destructive actions also need clear confirmation and visual distinction.' },
      { question: 'Are animated buttons good for conversion?', answer: 'Subtle feedback can improve clarity, but excessive movement can distract users and hurt usability. The label, placement, and offer matter more.' },
      { question: 'When should I use an icon-only button?', answer: 'Use icon-only buttons for familiar compact tools such as close, search, or download, and always provide an accessible label and tooltip.' },
    ],
    related: ['tailwind-css-components', 'form-components', 'modern-ui-components'],
  },
  {
    slug: 'form-components',
    title: 'Form UI Components',
    h1: 'Form components for clear, accessible product workflows',
    eyebrow: 'Input and form patterns',
    metaDescription: 'Explore form UI components for React and Next.js, including inputs, selects, validation, uploads, and multi-step product workflows.',
    description: 'Preview form controls and workflow patterns for onboarding, settings, checkout, account access, data entry, and search.',
    keywords: ['form UI components', 'React form components', 'Next.js forms', 'modern input components', 'Tailwind form components'],
    useCases: ['Onboarding', 'Account settings', 'Checkout', 'Search and filters', 'File uploads', 'Data entry'],
    introTitle: 'Forms need more than attractive inputs',
    intro: [
      'Useful forms explain what information is required, preserve user input, show errors close to the relevant field, and provide a clear completion state. Labels should remain visible and should not rely on placeholder text.',
      'Break long forms into meaningful steps only when it reduces cognitive load. Keep validation predictable and avoid blocking submission for formatting preferences that can be normalized automatically.',
    ],
    checklist: ['Persistent labels and useful help text', 'Field-level and form-level error summaries', 'Keyboard-friendly controls and logical tab order', 'Loading and success feedback after submission', 'Input values preserved after recoverable errors'],
    examples: [examples.input, component('Select Dropdown', 'select-dropdown-card', 'A structured select pattern for option sets.'), component('Upload Progress', 'upload-progress-card', 'File upload states with visible progress and completion feedback.'), component('Popover Form', 'popover-form-card', 'A compact form for contextual edits without leaving the current view.')],
    faqs: [
      { question: 'What makes a form component accessible?', answer: 'Use associated labels, clear instructions, keyboard-operable controls, programmatic error messages, sufficient contrast, and focus management after validation.' },
      { question: 'Should validation happen while typing?', answer: 'Use live validation for helpful format guidance, but avoid showing errors before a user has interacted with a field. Always validate again on submit.' },
      { question: 'Can these form components work with React Hook Form?', answer: 'The visual patterns can be integrated with React Hook Form or another form library by connecting values, validation, errors, and submission state.' },
    ],
    related: ['button-components', 'modal-components', 'react-ui-components', 'tailwind-css-components'],
  },
  {
    slug: 'modal-components',
    title: 'Modal and Dialog Components',
    h1: 'Modal and dialog components for focused product actions',
    eyebrow: 'Overlay components',
    metaDescription: 'Browse modal and dialog components for confirmation, onboarding, settings, uploads, quick views, and multi-step React workflows.',
    description: 'Compare focused overlay patterns for confirmations, compact edits, onboarding, quick views, and multi-step actions.',
    keywords: ['modal components', 'React modal component', 'dialog UI component', 'Next.js modal', 'confirmation dialog UI'],
    useCases: ['Confirmations', 'Quick edits', 'Onboarding', 'Settings', 'Product previews', 'Multi-step actions'],
    introTitle: 'Use a modal only when focus matters',
    intro: [
      'A modal interrupts the current page, so reserve it for actions that benefit from focused attention. Simple navigation or long content usually belongs on a normal route instead.',
      'Dialogs need a clear title, a direct next action, a safe cancellation path, focus containment, Escape handling, and focus restoration after closing.',
    ],
    checklist: ['Descriptive title and concise purpose', 'Focus trap and focus restoration', 'Escape and close controls', 'Safe cancellation path', 'Responsive size without nested page scrolling'],
    examples: [examples.modal, component('Multi-step Modal', 'multi-step-modal-card', 'A staged modal workflow for structured tasks.'), component('Settings Modal', 'settings-modal-card', 'A focused settings surface for compact product changes.'), component('Quick View Modal', 'quick-view-modal-card', 'A quick inspection pattern that preserves list context.')],
    faqs: [
      { question: 'When should I avoid using a modal?', answer: 'Avoid a modal for long reading, complex navigation, or tasks that need a shareable URL. Use a dedicated page when the workflow requires more space or history.' },
      { question: 'How do I make a modal keyboard accessible?', answer: 'Move focus into the dialog, keep focus within it while open, support Escape when appropriate, and restore focus to the trigger after closing.' },
      { question: 'Should confirmation dialogs be used for every delete action?', answer: 'Use confirmation when the consequence is significant or difficult to reverse. Undo can be a less disruptive choice for reversible actions.' },
    ],
    related: ['form-components', 'button-components', 'modern-ui-components'],
  },
  {
    slug: 'dashboard-ui-components',
    title: 'Dashboard UI Components',
    h1: 'Dashboard UI components for data-heavy products',
    eyebrow: 'Dashboard interface blocks',
    metaDescription: 'Explore dashboard UI components for analytics, admin panels, SaaS workspaces, tables, metrics, filters, and operational product interfaces.',
    description: 'Browse data display, navigation, filtering, command, and workflow components for admin dashboards and operational software.',
    keywords: ['dashboard UI components', 'admin dashboard components', 'React dashboard UI', 'SaaS dashboard components', 'Next.js dashboard components'],
    useCases: ['Analytics', 'Operations', 'Finance', 'CRM', 'Inventory', 'Admin panels'],
    introTitle: 'Design dashboards around decisions',
    intro: [
      'A dashboard should help users understand status and take action, not simply maximize the number of charts. Prioritize the few metrics, exceptions, and workflows that matter for the current role.',
      'Use stable card sizes, consistent number formatting, clear table controls, and intentional empty states. Dense interfaces can still feel calm when hierarchy and spacing remain predictable.',
    ],
    checklist: ['Metrics tied to a decision or workflow', 'Consistent date, currency, and number formatting', 'Tables with useful filters and empty states', 'Responsive layout that preserves priority', 'Accessible charts with textual context'],
    examples: [examples.dashboard, examples.table, examples.sidebar, examples.command, examples.notification, component('Year Wrapped Dashboard', 'year-wrapped-dashboard-card', 'A visual summary dashboard for periodic reporting.')],
    faqs: [
      { question: 'What components belong in an admin dashboard?', answer: 'Common patterns include navigation, summary metrics, filters, tables, activity feeds, notifications, forms, and focused actions. Include only what supports the product workflow.' },
      { question: 'How many metrics should a dashboard show?', answer: 'There is no fixed number. Show the smallest set that explains status and helps the user decide what to do next, with deeper detail available on focused pages.' },
      { question: 'Are these dashboard components responsive?', answer: 'The examples are designed with responsive behavior in mind, but every implementation should be tested with your real labels, data lengths, and supported viewports.' },
    ],
    related: ['sidebar-components', 'nextjs-ui-components', 'react-ui-components', 'modern-ui-components'],
  },
  {
    slug: 'landing-page-ui-blocks',
    title: 'Landing Page UI Blocks',
    h1: 'Landing page UI blocks for clear product storytelling',
    eyebrow: 'Marketing components',
    metaDescription: 'Browse landing page UI blocks for heroes, features, pricing, social proof, FAQs, calls to action, and responsive SaaS marketing pages.',
    description: 'Explore marketing sections for product launches, SaaS pages, ecommerce campaigns, and conversion-focused websites.',
    keywords: ['landing page UI blocks', 'SaaS UI blocks', 'hero section components', 'pricing components', 'React landing page components'],
    useCases: ['Product launches', 'SaaS marketing', 'Ecommerce campaigns', 'Developer tools', 'Waitlists', 'Service websites'],
    introTitle: 'Build a landing page around one clear offer',
    intro: [
      'A strong landing page explains the product, the audience, the outcome, and the next action in a logical sequence. Each section should answer a real buying question rather than repeat the same claim.',
      'Use product-specific screenshots, concise feature explanations, credible proof, transparent pricing, and focused calls to action. Keep the page fast and readable before adding decorative effects.',
    ],
    checklist: ['Literal offer and audience in the main heading', 'Product visuals that show the real experience', 'Benefits connected to concrete product capabilities', 'Clear pricing, trust, and support information', 'Focused calls to action with consistent wording'],
    examples: [examples.hero, examples.pricing, component('Bento CTA', 'cta-bento-card', 'A structured call-to-action block for product benefits and conversion.'), component('Contact Sales CTA', 'cta-contact-sales-card', 'A focused enterprise contact section with a clear next step.')],
    faqs: [
      { question: 'Which sections should a landing page include?', answer: 'Most product landing pages need a clear offer, product evidence, benefits, relevant features, trust or proof, pricing or next-step context, FAQs, and a focused call to action.' },
      { question: 'Do landing page components improve SEO by themselves?', answer: 'No. Search visibility also depends on helpful original content, crawlable page structure, metadata, internal links, performance, and whether the page satisfies a specific search intent.' },
      { question: 'Should every landing page use animation?', answer: 'No. Use motion only when it clarifies state or supports the story. Static, fast, well-structured pages often communicate more effectively.' },
    ],
    related: ['modern-ui-components', 'nextjs-ui-components', 'button-components', 'navbar-components'],
  },
  {
    slug: 'table-components',
    title: 'React Table and Data Grid Components',
    h1: 'Table components for dashboards and data-heavy products',
    eyebrow: 'Data display components',
    metaDescription: 'Preview React table and data grid components for sorting, filtering, responsive records, editable rows, permissions, invoices, and admin dashboards.',
    description: 'Compare practical table patterns for operational software, analytics, finance, inventory, permissions, and responsive product workflows.',
    keywords: ['React table components', 'data grid components', 'dashboard table UI', 'Next.js data table', 'Tailwind table components'],
    useCases: ['Admin records', 'Analytics', 'Inventory', 'Finance', 'Permissions', 'Customer management'],
    introTitle: 'Tables should make records easier to act on',
    intro: [
      'A useful data table helps people scan, compare, filter, and act without losing context. Column priority, alignment, formatting, density, and row actions should reflect the decisions users make with the data.',
      'Responsive tables need an explicit strategy rather than horizontal overflow by default. Preserve critical fields, move secondary details into expandable rows or compact cards, and keep sorting and selection behavior predictable.',
    ],
    checklist: ['Semantic headers and accessible labels', 'Useful empty, loading, and error states', 'Stable sorting, filtering, and pagination', 'Responsive column priority', 'Clear bulk and row-level actions'],
    examples: [component('Enterprise Table', 'enterprise-table-card', 'A dense enterprise table for operational records and row actions.'), component('Expandable Rows Table', 'expandable-rows-table-card', 'A table that reveals secondary record details without leaving context.'), component('Comparison Matrix', 'comparison-matrix-table-card', 'A structured matrix for comparing plans, permissions, or capabilities.'), component('Responsive Table', 'responsive-table-card', 'A record layout designed for smaller screens and changing widths.')],
    faqs: [
      { question: 'When should I use a data table?', answer: 'Use a table when users need to compare multiple records across consistent fields. Use cards or a list when each item has very different content or only one primary value.' },
      { question: 'How do tables work on mobile?', answer: 'Prioritize essential columns, expose secondary details through expandable rows or a card view, and keep row actions reachable without forcing users through a very wide canvas.' },
      { question: 'Should table filtering happen on the client?', answer: 'Small datasets can be filtered locally. Large or permission-sensitive datasets should use server-side filtering, sorting, and pagination with stable URL or state handling.' },
    ],
    related: ['dashboard-ui-components', 'react-ui-components', 'form-components'],
  },
  {
    slug: 'card-components',
    title: 'Modern Card UI Components',
    h1: 'Modern card components for products and websites',
    eyebrow: 'Content containers',
    metaDescription: 'Browse modern card UI components for SaaS dashboards, ecommerce, profiles, analytics, pricing, media, and responsive React interfaces.',
    description: 'Explore focused card patterns for summaries, actions, profiles, media, products, and dashboard data without turning every page section into a floating panel.',
    keywords: ['modern card UI', 'React card components', 'dashboard cards', 'Tailwind card components', 'SaaS card design'],
    useCases: ['Dashboard summaries', 'Product grids', 'Profiles', 'Media libraries', 'Pricing', 'Activity feeds'],
    introTitle: 'Use cards when content benefits from a boundary',
    intro: [
      'Cards work best for repeated items or self-contained tools that users need to scan and compare. A card should group related information, preserve a clear reading order, and expose one obvious next action.',
      'Avoid wrapping every section in another card. Strong page hierarchy, spacing, and full-width bands are often more useful than additional borders and shadows.',
    ],
    checklist: ['Clear heading and content hierarchy', 'Stable media dimensions', 'One primary action per card', 'Consistent repeated-item layout', 'Responsive text and overflow handling'],
    examples: [component('Analytics Insight Card', 'analytics-insight-card', 'A compact analytics summary with a decision-focused hierarchy.'), component('Animated Weather Card', 'animated-border-weather-card', 'A visual information card with stable content dimensions.'), component('Upload Progress Card', 'upload-progress-card', 'A task card for upload state, progress, and completion feedback.'), component('AI Generation Result', 'ai-generation-result-card', 'A result card for generated content and follow-up actions.')],
    faqs: [
      { question: 'When should I use a card component?', answer: 'Use cards for repeated, comparable, or self-contained items such as products, profiles, files, metrics, and saved content. Do not use a card only to decorate a normal page section.' },
      { question: 'How much content belongs in a card?', answer: 'Include enough information to identify the item and choose the next action. Move complex editing, long explanations, or deep navigation to a focused view.' },
      { question: 'Should cards all have the same height?', answer: 'Repeated grid cards usually scan better with stable dimensions. Use responsive constraints and line limits carefully without hiding information needed to make a decision.' },
    ],
    related: ['modern-ui-components', 'dashboard-ui-components', 'landing-page-ui-blocks'],
  },
  {
    slug: 'dropdown-components',
    title: 'Dropdown, Select, and Menu Components',
    h1: 'Dropdown components for clear option selection',
    eyebrow: 'Selection components',
    metaDescription: 'Preview React dropdown, select, command menu, and context menu components for forms, filters, navigation, and dashboard actions.',
    description: 'Compare selection patterns for compact option sets, searchable choices, filters, navigation, and contextual product commands.',
    keywords: ['dropdown components', 'React select component', 'Tailwind dropdown menu', 'Next.js dropdown', 'searchable select UI'],
    useCases: ['Form selection', 'Dashboard filters', 'Account menus', 'Command menus', 'Context actions', 'Navigation'],
    introTitle: 'Match the selection control to the task',
    intro: [
      'A dropdown saves space, but it also hides choices. Use it when options are familiar or secondary, and prefer visible controls when users need to compare a small set of important alternatives.',
      'Searchable selects need keyboard navigation, clear selected state, empty results, and reliable dismissal. Menus for commands should use action language, while form selects should represent values.',
    ],
    checklist: ['Keyboard navigation and visible focus', 'Selected, disabled, and empty states', 'Clear distinction between values and commands', 'Reliable outside-click and Escape behavior', 'Mobile-friendly touch targets and viewport positioning'],
    examples: [component('Dropdown Menu', 'dropdown-menu-card', 'A compact action menu with grouped commands and states.'), component('Select Dropdown', 'select-dropdown-card', 'A form selection pattern for structured values.'), examples.command, component('Context Menu', 'context-menu-card', 'A contextual command surface for product actions.')],
    faqs: [
      { question: 'Should I use a select or radio buttons?', answer: 'Use radio buttons when a small important set should remain visible. Use a select when options are numerous, familiar, or secondary to the main workflow.' },
      { question: 'What makes a dropdown accessible?', answer: 'It needs an accessible name, correct keyboard behavior, visible focus, announced selection, predictable dismissal, and focus return to the trigger.' },
      { question: 'Can a dropdown contain navigation links?', answer: 'Yes, account and product menus often contain links. Keep navigation links semantically distinct from buttons that perform immediate actions.' },
    ],
    related: ['form-components', 'navbar-components', 'modern-ui-components'],
  },
  {
    slug: 'tabs-accordion-components',
    title: 'Tabs and Accordion UI Components',
    h1: 'Tabs and accordion components for organized content',
    eyebrow: 'Content organization',
    metaDescription: 'Browse React tabs and accordion components for settings, FAQs, product details, dashboards, responsive content, and documentation interfaces.',
    description: 'Explore disclosure and view-switching patterns that organize related content while keeping navigation and state understandable.',
    keywords: ['React tabs component', 'accordion UI component', 'Tailwind tabs', 'FAQ accordion', 'Next.js tab component'],
    useCases: ['Settings', 'Product details', 'FAQs', 'Documentation', 'Dashboard views', 'Responsive content'],
    introTitle: 'Tabs switch views; accordions reveal details',
    intro: [
      'Tabs are useful for a small set of peer views within the same context. Accordions are better for independently expandable details, especially when users may need to scan several headings before opening one.',
      'Do not hide essential page content behind a default-closed control. Labels should describe the content clearly, state should remain visible, and keyboard behavior should follow familiar interface conventions.',
    ],
    checklist: ['Descriptive labels rather than generic numbering', 'Keyboard arrow behavior for tabs', 'Visible active and expanded state', 'Stable layout while content changes', 'Shareable routes when a view represents a distinct page'],
    examples: [component('Accordion', 'accordion-card', 'A general disclosure component for grouped details.'), component('Feature Accordion', 'feature-accordion-card', 'A feature explanation pattern for marketing and product pages.'), component('Card Table Switcher', 'card-table-switcher-card', 'A view switcher between card and table presentations.'), component('Tabs Interface', 'tabs-card', 'A compact peer-view navigation pattern.')],
    faqs: [
      { question: 'When should I use tabs?', answer: 'Use tabs for a small number of closely related peer views when users benefit from switching without leaving the current context.' },
      { question: 'When is an accordion better?', answer: 'Use an accordion for independently expandable details such as FAQs, configuration groups, or supporting explanations that users scan by heading.' },
      { question: 'Do hidden tab panels affect SEO?', answer: 'Important public content should remain available in rendered HTML and be organized for users first. Distinct search intents usually deserve crawlable pages rather than being hidden in a large tab set.' },
    ],
    related: ['landing-page-ui-blocks', 'modern-ui-components', 'dashboard-ui-components'],
  },
  {
    slug: 'loading-skeleton-components',
    title: 'Loading and Skeleton UI Components',
    h1: 'Loading components that keep product state understandable',
    eyebrow: 'Feedback components',
    metaDescription: 'Preview loading indicators, skeleton components, progress UI, and button loading states for React, Next.js, uploads, and asynchronous product workflows.',
    description: 'Find stable loading patterns for route transitions, data fetches, uploads, form actions, and generated content without causing layout shifts.',
    keywords: ['loading components', 'React skeleton component', 'Next.js loading UI', 'progress indicator UI', 'loading button component'],
    useCases: ['Route loading', 'Data fetching', 'File uploads', 'Checkout', 'Form submission', 'AI generation'],
    introTitle: 'Loading feedback should explain what is happening',
    intro: [
      'Use immediate feedback for actions that take noticeable time. Skeletons work for predictable content layouts, progress bars work when completion can be measured, and compact spinners work for short actions with clear surrounding context.',
      'Keep dimensions stable so loading content does not shift the page. Prevent duplicate submissions, preserve accessible status text, and provide recovery when an operation takes too long or fails.',
    ],
    checklist: ['Stable dimensions that prevent layout shift', 'Accessible status text or live region', 'Duplicate-action prevention', 'Measured progress only when it is real', 'Timeout and error recovery'],
    examples: [component('Loading Skeletons', 'loading-skeletons-card', 'Structured placeholders for predictable content layouts.'), component('Loading State Buttons', 'loading-state-buttons-card', 'Buttons that preserve their size and label context while processing.'), component('Upload Progress', 'upload-progress-card', 'File progress with active, complete, and error feedback.'), component('Progress Indicator', 'progress-bar-card', 'A determinate progress pattern for measurable tasks.')],
    faqs: [
      { question: 'Should I use a spinner or skeleton?', answer: 'Use a skeleton when the final layout is predictable and takes time to populate. Use a spinner for short focused operations where a content-shaped placeholder would be misleading.' },
      { question: 'How long before loading feedback appears?', answer: 'Immediate actions should feel instant, but any noticeable delay needs feedback. Avoid flashing a skeleton for very fast responses by using a short, carefully tested delay where appropriate.' },
      { question: 'Can a progress bar show estimated progress?', answer: 'Only label it clearly as estimated. A determinate percentage should be based on real measurable progress so users are not misled.' },
    ],
    related: ['button-components', 'form-components', 'modern-ui-components'],
  },
  {
    slug: 'pricing-components',
    title: 'Pricing Table and Plan Components',
    h1: 'Pricing components for clear plan comparison',
    eyebrow: 'Commerce components',
    metaDescription: 'Browse pricing table and plan card components for SaaS, template stores, subscriptions, one-time products, feature comparison, and checkout calls to action.',
    description: 'Compare pricing layouts that communicate product scope, billing terms, included features, and a clear purchase action without hiding important conditions.',
    keywords: ['pricing components', 'React pricing table', 'SaaS pricing UI', 'pricing card component', 'Tailwind pricing section'],
    useCases: ['SaaS plans', 'One-time products', 'Template stores', 'Memberships', 'Feature comparison', 'Checkout'],
    introTitle: 'Pricing UI should reduce uncertainty',
    intro: [
      'A pricing section should state what the buyer receives, how often they pay, which limits apply, and what happens after checkout. Visual emphasis must support a genuine recommendation rather than conceal alternatives.',
      'Keep plan names, prices, billing periods, taxes, feature differences, and calls to action easy to compare. Put important exclusions near the decision instead of hiding them in distant copy.',
    ],
    checklist: ['Price and billing period shown together', 'Clear included and excluded scope', 'Comparable feature language', 'Honest recommendation labels', 'Purchase action and post-checkout expectation'],
    examples: [examples.pricing, component('Pricing Upgrade CTA', 'cta-pricing-upgrade-card', 'An account upgrade prompt with plan context.'), component('Pricing Plan', 'pricing-plan-card', 'A focused plan card for product access and features.'), component('Pricing Comparison', 'pricing004-card', 'A multi-plan layout for side-by-side feature comparison.')],
    faqs: [
      { question: 'What should a pricing component include?', answer: 'Include the product or plan name, total or recurring price, billing period, scope, meaningful limits, key features, and a clear purchase or contact action.' },
      { question: 'Should the recommended plan be larger?', answer: 'It can be emphasized, but all plans should remain readable and comparable. The recommendation should reflect a real audience need rather than pressure users.' },
      { question: 'Where should refund and license information appear?', answer: 'Summarize decision-critical terms near pricing and link to complete policies. Buyers should understand purchase scope before checkout.' },
    ],
    related: ['landing-page-ui-blocks', 'button-components', 'modern-ui-components'],
  },
  {
    slug: 'hero-section-components',
    title: 'Modern Hero Section Components',
    h1: 'Hero section components for product and business websites',
    eyebrow: 'Opening page sections',
    metaDescription: 'Preview modern hero section components for SaaS, ecommerce, portfolios, agencies, developer tools, and responsive React landing pages.',
    description: 'Explore focused opening sections that establish the product, audience, value, visual evidence, and next action in the first viewport.',
    keywords: ['hero section components', 'modern website hero', 'React hero component', 'SaaS hero section', 'Tailwind hero component'],
    useCases: ['SaaS websites', 'Ecommerce', 'Portfolios', 'Agencies', 'Developer tools', 'Product launches'],
    introTitle: 'A hero should identify the offer immediately',
    intro: [
      'The main heading should name the product, service, person, or literal offer. Supporting copy can explain the audience and outcome, while the primary visual should show the actual product, work, place, or experience.',
      'Keep the first viewport focused. One primary call to action, one supporting action when necessary, and a visible hint of the next section usually communicate more than a crowded collection of badges and effects.',
    ],
    checklist: ['Literal product or offer in the heading', 'Specific supporting value proposition', 'Relevant visual evidence', 'One clear primary action', 'Responsive height with the next section visible'],
    examples: [examples.hero, component('SaaS Hero', 'hero003-card', 'A product-led hero for SaaS and software offers.'), component('Editorial Hero', 'hero006-card', 'A type-led opening section for creative and editorial sites.'), component('Product Hero', 'hero008-card', 'A visual product opening with a focused purchase path.')],
    faqs: [
      { question: 'What belongs in a website hero section?', answer: 'Include a literal offer or product name, a concise value proposition, relevant visual evidence, and one clear primary action.' },
      { question: 'Should a hero fill the whole screen?', answer: 'Not always. Leave a visible hint of the next section so users understand there is more content, especially on mobile and wide desktop screens.' },
      { question: 'Does a hero need animation?', answer: 'No. Use motion only when it explains the product or state. Strong copy, real visuals, fast loading, and stable layout matter more.' },
    ],
    related: ['landing-page-ui-blocks', 'navbar-components', 'pricing-components'],
  },
  {
    slug: 'authentication-components',
    title: 'Authentication UI Components',
    h1: 'Authentication components for clear account access',
    eyebrow: 'Account components',
    metaDescription: 'Browse sign-in, sign-up, password reset, OAuth, verification, and account access UI components for React and Next.js products.',
    description: 'Compare authentication screens and states for account creation, sign-in, OAuth, recovery, security feedback, and post-authentication routing.',
    keywords: ['authentication UI components', 'React login component', 'Next.js sign in page', 'signup form UI', 'password reset component'],
    useCases: ['Sign in', 'Account creation', 'OAuth', 'Password recovery', 'Checkout return', 'Protected products'],
    introTitle: 'Authentication UI should preserve user intent',
    intro: [
      'Account access is a transition, not the destination. After successful sign-in or registration, return users to the template, checkout, download, or workspace they originally requested.',
      'Forms need clear labels, useful error messages, password manager support, loading protection, and recovery paths. OAuth actions should explain the provider without exposing configuration details.',
    ],
    checklist: ['Return to the intended page after success', 'Password manager and autocomplete support', 'Clear field and provider errors', 'Loading state that prevents duplicate submissions', 'Accessible recovery and sign-out paths'],
    examples: [examples.auth, component('Split Authentication', 'auth003-card', 'A split-layout account access screen for product brands.'), component('Compact Sign In', 'auth006-card', 'A focused sign-in experience for application access.'), component('Account Recovery', 'auth009-card', 'An authentication flow with clear recovery context.')],
    faqs: [
      { question: 'What fields should a sign-up form ask for?', answer: 'Ask only for information needed to create and secure the account. Additional profile details can be collected later when they become relevant.' },
      { question: 'Should sign-in and sign-up share one page?', answer: 'They can, but the current mode and primary action must be unmistakable. Dedicated routes are often easier to link, track, and return users to.' },
      { question: 'What happens after OAuth sign-in?', answer: 'Create the application session, preserve the provider profile data you actually need, and return the user to the original protected action or page.' },
    ],
    related: ['form-components', 'button-components', 'nextjs-ui-components'],
  },
  {
    slug: 'toast-notification-components',
    title: 'Toast and Notification UI Components',
    h1: 'Toast and notification components for product feedback',
    eyebrow: 'Status and activity components',
    metaDescription: 'Preview toast, notification, alert, activity, and status components for React dashboards, account events, downloads, forms, and checkout feedback.',
    description: 'Explore temporary and persistent feedback patterns for completed actions, errors, account events, downloads, and product activity.',
    keywords: ['toast components', 'React notification component', 'alert UI component', 'dashboard notification UI', 'Tailwind toast'],
    useCases: ['Form feedback', 'Download status', 'Checkout events', 'Account activity', 'System alerts', 'Background tasks'],
    introTitle: 'Choose feedback based on urgency and persistence',
    intro: [
      'Use a toast for brief confirmation that does not require immediate action. Persistent errors, security issues, or information users need to revisit belong in an alert, inline message, notification center, or dedicated status surface.',
      'Messages should state what happened and what the user can do next. Keep placement consistent, announce important updates accessibly, and avoid stacking so many temporary notices that actions become difficult to follow.',
    ],
    checklist: ['Message states what happened', 'Action or recovery when needed', 'Appropriate persistence for severity', 'Accessible status announcement', 'Mobile placement that avoids navigation and checkout controls'],
    examples: [component('Toast System', 'toast-system-card', 'A queued toast pattern for temporary product feedback.'), examples.notification, component('Alert', 'delete-alert-card', 'A persistent message for important page-level status.'), component('Activity Feed', 'notification-inbox-card', 'A chronological record of product and account events.')],
    faqs: [
      { question: 'When should I use a toast?', answer: 'Use a toast for brief confirmation or low-risk status that users do not need to revisit, such as a saved preference or copied value.' },
      { question: 'How long should a toast remain visible?', answer: 'Keep simple confirmations visible long enough to read. Errors or notices with actions should persist or be placed inline instead of disappearing automatically.' },
      { question: 'Where should notifications appear on mobile?', answer: 'Use a safe viewport area that does not cover bottom navigation, keyboards, checkout controls, or other critical actions.' },
    ],
    related: ['modern-ui-components', 'dashboard-ui-components', 'loading-skeleton-components'],
  }
]

export function getUiComponentSeoHub(slug: string) {
  return UI_COMPONENT_SEO_HUBS.find((hub) => hub.slug === slug)
}

export function getUiComponentPreviewUrl(slug: string) {
  const baseUrl = (process.env.NEXT_PUBLIC_UI_LIBRARY_URL || 'https://ui.mtverse.dev').replace(/\/$/, '')
  return `${baseUrl}/components/cards/${slug}`
}
