import type { Metadata } from 'next'
import { LegalPage, legalMetadata } from '@/components/legal/legal-page'

export const metadata: Metadata = legalMetadata(
  'Disclaimer',
  'Important disclaimers and limitations for mtverse services and content.',
  '/disclaimer'
)

export default function DisclaimerPage() {
  return (
    <LegalPage
      title="Disclaimer"
      description="Important disclaimers regarding our service and content."
      lastUpdated="June 27, 2026"
    >
      <h2>General Information</h2>
      <p>
        The information provided by mtverse on mtverse.dev is for general informational purposes only. All information on the Service
        is provided in good faith, however we make no representation or warranty of any kind, express or implied, regarding the accuracy,
        adequacy, validity, reliability, availability, or completeness of any information on the Service.
      </p>

      <h2>AI Prompts Disclaimer</h2>
      <p>
        The AI prompts available on our Service are provided for informational and creative purposes only. Results may vary depending on
        the AI model used, input parameters, and other factors. We do not guarantee specific results from using any prompt.
      </p>
      <p>
        You are solely responsible for reviewing and complying with the terms of service of any AI tool you use with our prompts,
        including but not limited to ChatGPT, Midjourney, Flux, Gemini, Claude, and Photoshop AI.
      </p>

      <h2>Templates Disclaimer</h2>
      <p>
        Our premium templates are provided as-is. While we test every template before release, we cannot guarantee that every template
        will work perfectly in every environment or use case. You are responsible for testing templates in your own environment before
        deploying to production.
      </p>

      <h2>External Links Disclaimer</h2>
      <p>
        The Service may contain links to other websites or content belonging to or originating from third parties. Such external links
        are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us.
      </p>

      <h2>Professional Disclaimer</h2>
      <p>
        The Service does not contain professional advice of any kind. The prompts and templates provided are not a substitute for
        professional advice. You should consult with a qualified professional before making decisions based on any content from the Service.
      </p>

      <h2>Testimonials Disclaimer</h2>
      <p>
        The Service may contain testimonials from users. These testimonials reflect the real-life experiences and opinions of such users.
        However, the experiences are personal to those particular users, and may not necessarily be representative of all users of our products.
      </p>

      <h2>Errors and Omissions Disclaimer</h2>
      <p>
        While we strive to keep the information on the Service up-to-date and accurate, errors may occur. mtverse is not responsible for
        any errors or omissions, or for the results obtained from the use of this information.
      </p>

      <h2>Fair Use Disclaimer</h2>
      <p>
        The Service may contain copyrighted material not specifically authorized by the copyright owner. We believe this constitutes a
        &quot;fair use&quot; of any such copyrighted material as provided for in section 107 of the United States Copyright Law.
      </p>

      <h2>Views Expressed Disclaimer</h2>
      <p>
        The Service may contain views and opinions which are those of the authors and do not necessarily reflect the official policy or
        position of any other author, agency, organization, employer, or company, including mtverse.
      </p>

      <h2>No Responsibility for AI-Generated Content</h2>
      <p>
        mtverse is not responsible for any content generated by AI models using our prompts. Users are solely responsible for reviewing,
        verifying, and ensuring the legality and appropriateness of any AI-generated content before publishing or distributing it.
      </p>

      <h2>Contact Us</h2>
      <p>For questions about this Disclaimer, please contact us at <a href="mailto:legal@mtverse.dev">legal@mtverse.dev</a>.</p>
    </LegalPage>
  )
}
